name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo hi >> hello.txt
      - name: Auto Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: latest
          draft: true
          # title: optional
          files: |
            hello.txt
